apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-server
  namespace: mlflow
  labels:
    app: mlflow-server

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-server
  template:
    metadata:
      labels:
        app: mlflow-server
    spec:
      containers:
        - name: mlflow-server
          image: ghcr.io/mlflow/mlflow:v2.20.1
          command: 
            - mlflow 
            - server
          resources:
            requests:
              memory: "1024Mi"
              cpu: "1000m"
            limits:
              memory: "2048Mi"
              cpu: "5000m"
          ports:
            - containerPort: 5000
          env:
            - name: MLFLOW_BACKEND_STORE_URI
              value: sqlite:///mlflow.db
            - name: MLFLOW_HOST
              value: "0.0.0.0"
            - name: MLFLOW_PORT
              value: "5000"
            
          volumeMounts:
            - mountPath: mnt/
              name: mlflow-backend-store
      volumes:
        - name: mlflow-backend-store
          emptyDir: {} 
    