apiVersion: v1 
kind: Service
metadata:
  name: mlflow-server
  namespace: mlflow 
spec:
  type: NodePort
  selector:
    app: mlflow-server
  ports:
  - nodePort: 32410
    protocol: TCP
    port: 80
    targetPort: 5000
  